export type Tier = 'prestige' | 'superior' | 'deluxe' | 'enhanced' | 'standard'
export type Faction = 'MIDA' | 'NuCaloric' | 'Traxus' | 'Arachne' | 'Sekiguchi' | 'CyberAcme'

export interface Source {
  map: string
  locations: string[]
  note?: string
}

export interface Material {
  id: string
  name: string
  image: string
  tier: Tier
  value: number
  description: string
  salvageType: string[]
  sources: Source[]
  usedBy: string[]
}

export const TIER_ORDER: Tier[] = ['prestige', 'superior', 'deluxe', 'enhanced', 'standard']

export const TIER_COLORS: Record<Tier, string> = {
  prestige: 'text-yellow-400 border-yellow-400',
  superior: 'text-purple-400 border-purple-400',
  deluxe: 'text-blue-400 border-blue-400',
  enhanced: 'text-green-400 border-green-400',
  standard: 'text-gray-400 border-gray-400',
}

export const TIER_BG: Record<Tier, string> = {
  prestige: 'bg-yellow-400/10',
  superior: 'bg-purple-400/10',
  deluxe: 'bg-blue-400/10',
  enhanced: 'bg-green-400/10',
  standard: 'bg-gray-400/10',
}

export const materials: Material[] = [
  // PRESTIGE
  {
    id: 'alien-alloy',
    name: 'Alien Alloy',
    image: '/images/Alien_Alloy.webp',
    tier: 'prestige',
    value: 4000,
    description: 'An unusual material with metallic and biological properties.',
    salvageType: ['Eccentric'],
    sources: [
      { map: 'Cryo Archive', locations: [] },
      { map: 'Lockdown Zones', locations: [] },
      { map: 'Intercept', locations: [] },
      { map: 'Convoy', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Prestige tier. Guaranteed one on a shelf by a window in Perimeter South Relay Observatory Gold Key Room.' },
    ],
    usedBy: ['MIDA Upgrades and Barters'],
  },
  {
    id: 'hazard-capsule',
    name: 'Hazard Capsule',
    image: '/images/Hazard_Capsule.webp',
    tier: 'prestige',
    value: 4000,
    description: 'A hermetically sealed container filled with an extremely volatile substance.',
    salvageType: ['Eccentric'],
    sources: [
      { map: 'Cryo Archive', locations: [] },
      { map: 'Lockdown Zones', locations: [] },
      { map: 'Intercept', locations: [] },
      { map: 'Convoy', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Prestige tier. Guaranteed one on the floor of AI Uplink Server Room & one inside a basket by the door on the south entrance of the Greenhouse Lab.' },
    ],
    usedBy: ['NuCaloric Upgrades and Barters'],
  },
  {
    id: 'synapse-cube',
    name: 'Synapse Cube',
    image: '/images/Synapse_Cube.webp',
    tier: 'prestige',
    value: 4000,
    description: 'Essential for integrating the electrical signals within a cyborg shell.',
    salvageType: ['Eccentric'],
    sources: [
      { map: 'Cryo Archive', locations: [] },
      { map: 'Lockdown Zones', locations: [] },
      { map: 'Intercept', locations: [] },
      { map: 'Convoy', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Prestige tier.' },
    ],
    usedBy: ['Arachne Upgrades and Barters'],
  },

  // SUPERIOR
  {
    id: 'ballistic-turbine',
    name: 'Ballistic Turbine',
    image: '/images/Ballistic_Turbine.webp',
    tier: 'superior',
    value: 1000,
    description: 'Rods/Compounds Salvage. A positive displacement turbine alternative.',
    salvageType: ['Rod', 'Compound'],
    sources: [
      { map: 'Dire Marsh', locations: ['Complex', 'Maintenance'] },
      { map: 'Outpost', locations: ['Airfield'] },
      { map: 'Cryo Archive', locations: ['Index'] },
      { map: 'Lockdown Zones', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Superior or higher.' },
    ],
    usedBy: ['Traxus Upgrades and Barters', 'MIDA Upgrades and Barters'],
  },
  {
    id: 'biolens-seed',
    name: 'Biolens Seed',
    image: '/images/Biolens_Seed.webp',
    tier: 'superior',
    value: 1000,
    description: 'Lens/Plant Salvage. Organic focusing medium used in the construction of biological lasers.',
    salvageType: ['Lens', 'Plant'],
    sources: [
      { map: 'Perimeter', locations: ['Overflow'], note: 'Guaranteed one in the Overflow Laboratory locked room, in the center growing area.' },
      { map: 'Dire Marsh', locations: ['Quarantine', 'Greenhouse'] },
      { map: 'Cryo Archive', locations: ['Revival'] },
      { map: 'Lockdown Zones', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Superior or higher.' },
    ],
    usedBy: ['NuCaloric Upgrades and Barters', 'MIDA Upgrades and Barters'],
  },
  {
    id: 'enzyme-replicator',
    name: 'Enzyme Replicator',
    image: '/images/Enzyme_Replicator.webp',
    tier: 'superior',
    value: 1000,
    description: 'Node/Chempack Salvage. Complex biological exosystem capable of prolonging life.',
    salvageType: ['Node', 'Chempack'],
    sources: [
      { map: 'Outpost', locations: ['Orientation', 'Pinwheel Base', 'Processing'] },
      { map: 'Cryo Archive', locations: ['Steerage'] },
      { map: 'Lockdown Zones', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Superior or higher.' },
    ],
    usedBy: ['Arachne Upgrades and Barters'],
  },
  {
    id: 'reflex-coil',
    name: 'Reflex Coil',
    image: '/images/Reflex_Coil.webp',
    tier: 'superior',
    value: 1000,
    description: 'Filament/Resin Salvage. A spool of myelin-coated filament for use in biological synthetics.',
    salvageType: ['Filament', 'Resin'],
    sources: [
      { map: 'Dire Marsh', locations: ['AI Uplink', 'Bio-Research'] },
      { map: 'Cryo Archive', locations: ['Cargo'] },
      { map: 'Lockdown Zones', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Superior or higher.' },
    ],
    usedBy: ['NuCaloric Upgrades and Barters', 'Arachne Upgrades and Barters'],
  },
  {
    id: 'neural-insulation',
    name: 'Neural Insulation',
    image: '/images/Neural_Insulation.webp',
    tier: 'superior',
    value: 1000,
    description: 'Biostrip/Circuit Salvage. Specialized material for insulation neural processes during transfer.',
    salvageType: ['Biostrip', 'Circuit'],
    sources: [
      { map: 'Perimeter', locations: ['North Relay', 'Hauler'] },
      { map: 'Dire Marsh', locations: ['Algae Ponds'] },
      { map: 'Outpost', locations: ['Flight Control', 'Dormitories'] },
      { map: 'Cryo Archive', locations: ['Preservation'] },
      { map: 'Lockdown Zones', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Superior or higher.' },
    ],
    usedBy: ['NuCaloric Upgrades', 'NuCaloric Vendor Unlocks', 'Traxus Vendor Unlocks'],
  },
  {
    id: 'predictive-framework',
    name: 'Predictive Framework',
    image: '/images/Predictive_Framework.webp',
    tier: 'superior',
    value: 1000,
    description: 'Drive/Wire Salvage. Wiring capable of anticipating inputs before they happen.',
    salvageType: ['Drive', 'Wire'],
    sources: [
      { map: 'Perimeter', locations: ['Station', 'South Relay'] },
      { map: 'Cryo Archive', locations: ['Biostock'] },
      { map: 'Lockdown Zones', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Superior or higher.' },
    ],
    usedBy: ['Traxus Upgrades and Barters', 'Sekiguchi Upgrades and Barters'],
  },

  // DELUXE
  {
    id: 'amygdala-drive',
    name: 'Amygdala Drive',
    image: '/images/Amygdala_Drive.webp',
    tier: 'deluxe',
    value: 300,
    description: 'Drive Salvage. Advanced storage drive able to mimic biological memory response.',
    salvageType: ['Drive'],
    sources: [
      { map: 'Perimeter', locations: ['South Relay'] },
      { map: 'Core Storage', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['Sekiguchi Upgrades and Barters'],
  },
  {
    id: 'anomalous-wire',
    name: 'Anomalous Wire',
    image: '/images/Anomalous_Wire.webp',
    tier: 'deluxe',
    value: 300,
    description: "Wire Salvage. Wire exposed to Tau Ceti IV's anomalous energies, resulting in instantaneous data transfer.",
    salvageType: ['Wire'],
    sources: [
      { map: 'Perimeter', locations: ['Station'] },
      { map: 'Cryo Archive', locations: ['Biostock'] },
      { map: 'Munitions Crate', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['Traxus Upgrades and Barters'],
  },
  {
    id: 'biomata-node',
    name: 'Biomata Node',
    image: '/images/Biomata_Node.webp',
    tier: 'deluxe',
    value: 300,
    description: 'Node Salvage. A cybernetic node from a biomata, containing unknown potential.',
    salvageType: ['Node'],
    sources: [
      { map: 'Dire Marsh', locations: ['Bio-Research'] },
      { map: 'Tool Cart', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['Arachne Upgrades and Barters'],
  },
  {
    id: 'biomata-resin',
    name: 'Biomata Resin',
    image: '/images/Biomata_Resin.webp',
    tier: 'deluxe',
    value: 300,
    description: 'Resin Salvage. A powerful adhesive suitable for affixing living flesh to synthetic bone.',
    salvageType: ['Resin'],
    sources: [
      { map: 'Outpost', locations: ['Orientation', 'Pinwheel Base', 'Processing'] },
      { map: 'Tool Cart', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['Arachne Upgrades and Barters'],
  },
  {
    id: 'centinite-rods',
    name: 'Centinite Rods',
    image: '/images/Centinite_Rods.webp',
    tier: 'deluxe',
    value: 300,
    description: 'Rod Salvage. Rods smelted from strange alloy the colonists harvested from Tau Ceit IV prior to their disappearance.',
    salvageType: ['Rod'],
    sources: [
      { map: 'Dire Marsh', locations: ['Maintenance'] },
      { map: 'Cryo Archive', locations: ['Index'] },
      { map: 'Arms Locker', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['Traxus Upgrades and Barters'],
  },
  {
    id: 'neurochem-pack',
    name: 'Neurochem Pack',
    image: '/images/Neurochem_Pack.webp',
    tier: 'deluxe',
    value: 50,
    description: 'Chempack Salvage. Packet of neurological chemicals used to enhance biomata and other cyber-organic accessories.',
    salvageType: ['Chempack'],
    sources: [
      { map: 'Outpost', locations: ['Pinwheel'] },
      { map: 'Medical Cabinet', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['NuCaloric Upgrades and Barters'],
  },
  {
    id: 'paradox-circuit',
    name: 'Paradox Circuit',
    image: '/images/Paradox_Circuit.webp',
    tier: 'deluxe',
    value: 300,
    description: 'Circuit Salvage. A processor capable of creating a more powerful version of itself, known as a Paradox Circuit.',
    salvageType: ['Circuit'],
    sources: [
      { map: 'Perimeter', locations: ['North Relay'] },
      { map: 'Outpost', locations: ['Flight Control', 'Dormitories', 'Pinwheel Base'] },
      { map: 'Core Storage', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['Sekiguchi Upgrades and Barters'],
  },
  {
    id: 'sterilized-biostripping',
    name: 'Sterilized Biostripping',
    image: '/images/Sterilized_Biostripping.webp',
    tier: 'deluxe',
    value: 300,
    description: 'Biostrip Salvage. Advanced material made of reclaimed waste and treated with a powerful bioagent, making it safe to handle.',
    salvageType: ['Biostrip'],
    sources: [
      { map: 'Perimeter', locations: ['Hauler'] },
      { map: 'Dire Marsh', locations: ['Algae Ponds'] },
      { map: 'Arms Locker', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['CyberAcme Upgrades', 'NuCaloric Market Access', 'Traxus Market Access'],
  },
  {
    id: 'tarax-seed',
    name: 'Tarax Seed',
    image: '/images/Tarax_Seed.webp',
    tier: 'deluxe',
    value: 300,
    description: 'Plant Salvage. Mildly toxic when eaten, but pharmaceuticals can be extracted from the seeds.',
    salvageType: ['Plant'],
    sources: [
      { map: 'Perimeter', locations: ['Overflow'] },
      { map: 'Dire Marsh', locations: ['Greenhouse'] },
      { map: 'Medical Cabinet', locations: [] },
      { map: 'Grassy Areas', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['NuCaloric Upgrades and Barters'],
  },
  {
    id: 'tachyon-filament',
    name: 'Tachyon Filament',
    image: '/images/Tachyon_Filament.webp',
    tier: 'deluxe',
    value: 300,
    description: 'Filament Salvage. Filament that can form itself into intended arrangements of its own accord.',
    salvageType: ['Filament'],
    sources: [
      { map: 'Dire Marsh', locations: ['AI Uplink'] },
      { map: 'Bioprinter', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['Traxus Upgrades and Barters'],
  },
  {
    id: 'thoughtwave-lens',
    name: 'Thoughtwave Lens',
    image: '/images/Toughtwave_Lens.webp',
    tier: 'deluxe',
    value: 300,
    description: "Lens Salvage. Surveillance equipment able to record impressions of subject's thoughts.",
    salvageType: ['Lens'],
    sources: [
      { map: 'Dire Marsh', locations: ['Quarantine'] },
      { map: 'Bioprinter', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['MIDA Upgrades and Barters'],
  },
  {
    id: 'volatile-compounds',
    name: 'Volatile Compounds',
    image: '/images/Volatile_Compounds.webp',
    tier: 'deluxe',
    value: 300,
    description: 'Compound Salvage. Highly unpredictable chemicals in an ergonomic carrying case.',
    salvageType: ['Compound'],
    sources: [
      { map: 'Dire Marsh', locations: ['Complex'] },
      { map: 'Outpost', locations: ['Airfield', 'Pinwheel Base'] },
      { map: 'Munitions Crate', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['MIDA Upgrades and Barters'],
  },

  // ENHANCED
  {
    id: 'altered-wire',
    name: 'Altered Wire',
    image: '/images/Altered_Wire.webp',
    tier: 'enhanced',
    value: 50,
    description: 'Wire Salvage. Wiring influenced by unknown energies, causing bursts of superconductive capacity.',
    salvageType: ['Wire'],
    sources: [
      { map: 'Perimeter', locations: ['Station'] },
      { map: 'Munitions Crate', locations: [] },
      { map: 'Locked Rooms', locations: [], note: 'Deluxe or higher.' },
    ],
    usedBy: ['Traxus Upgrades and Barters'],
  },
  {
    id: 'dynamic-compounds',
    name: 'Dynamic Compounds',
    image: '/images/Dynamic_Compounds.webp',
    tier: 'enhanced',
    value: 50,
    description: 'Compound Salvage. Lightweight, reliable, and easily recycled.',
    salvageType: ['Compound'],
    sources: [
      { map: 'Dire Marsh', locations: ['Complex'] },
    ],
    usedBy: ['MIDA Upgrades and Barters'],
  },
  {
    id: 'deimosite-rods',
    name: 'Deimosite Rods',
    image: '/images/Deimosite_Rods.webp',
    tier: 'enhanced',
    value: 50,
    description: 'Rod Salvage. Stout rods made from material mined from Deimos itself.',
    salvageType: ['Rod'],
    sources: [
      { map: 'Dire Marsh', locations: ['Maintenance'] },
      { map: 'Arms Locker', locations: [] },
    ],
    usedBy: ['Traxus Upgrades and Barters'],
  },
  {
    id: 'dermachem-pack',
    name: 'Dermachem Pack',
    image: '/images/Dermachem_Pack.webp',
    tier: 'enhanced',
    value: 50,
    description: 'Chempack Salvage. Synthetic chemical substrate able to add a fleshlike conductive layer to inorganic materials.',
    salvageType: ['Chempack'],
    sources: [
      { map: 'Outpost', locations: ['Pinwheel Base'] },
      { map: 'Medical Cabinet', locations: [] },
    ],
    usedBy: ['NuCaloric Upgrades and Barters'],
  },
  {
    id: 'drone-node',
    name: 'Drone Node',
    image: '/images/Drone_Node.webp',
    tier: 'enhanced',
    value: 50,
    description: 'Node Salvage. A digital node from a drone capable of independent thought.',
    salvageType: ['Node'],
    sources: [
      { map: 'Outpost', locations: ['Orientation', 'Pinwheel Base', 'Processing'] },
      { map: 'Tool Cart', locations: [] },
    ],
    usedBy: ['Arachne Upgrades and Barters'],
  },
  {
    id: 'drone-resin',
    name: 'Drone Resin',
    image: '',
    tier: 'enhanced',
    value: 50,
    description: 'Resin Salvage.',
    salvageType: ['Resin'],
    sources: [],
    usedBy: [],
  },
  {
    id: 'fractal-circuit',
    name: 'Fractal Circuit',
    image: '/images/Fractal_Circuit.webp',
    tier: 'enhanced',
    value: 50,
    description: 'Circuit Salvage. Digital processor able to exponentially increase speed and storage.',
    salvageType: ['Circuit'],
    sources: [
      { map: 'Perimeter', locations: ['North Relay'] },
      { map: 'Outpost', locations: ['Flight Control', 'Dormitories', 'Pinwheel Base'] },
      { map: 'Core Storage', locations: [] },
    ],
    usedBy: ['Sekiguchi Upgrades and Barters'],
  },
  {
    id: 'plasma-filament',
    name: 'Plasma Filament',
    image: '/images/Plasma_Filament.webp',
    tier: 'enhanced',
    value: 10,
    description: 'Filament Salvage. Ubiquitous wherever fabrication needs to be fast, cheap, and reliable.',
    salvageType: ['Filament'],
    sources: [
      { map: 'Perimeter', locations: ['North Relay', 'Overflow'] },
      { map: 'Bioprinter', locations: [] },
    ],
    usedBy: ['NuCaloric Upgrades', 'NuCaloric Vendor Unlocks', 'Traxus Vendor Unlocks'],
  },
  {
    id: 'reclaimed-biostripping',
    name: 'Reclaimed Biostripping',
    image: '/images/Reclaimed_Biostripping.webp',
    tier: 'enhanced',
    value: 10,
    description: 'Biostrip Salvage. Useful rubberlike material sourced from reclaimed biological waste.',
    salvageType: ['Biostrip'],
    sources: [
      { map: 'Perimeter', locations: ['Hauler'] },
      { map: 'Dire Marsh', locations: ['Algae Ponds'] },
      { map: 'Arms Locker', locations: [] },
    ],
    usedBy: ['CyberAcme Upgrades', 'NuCaloric Market Access', 'Traxus Market Access'],
  },
  {
    id: 'spark-leaf',
    name: 'Spark Leaf',
    image: '/images/Spark_Leaf.webp',
    tier: 'enhanced',
    value: 10,
    description: 'Plant Salvage. High in silica content, making this plant a valuable resource on Tau Ceti IV.',
    salvageType: ['Plant'],
    sources: [
      { map: 'Perimeter', locations: ['Grassy Areas'] },
      { map: 'Dire Marsh', locations: ['AI Uplink', 'Greenhouse', 'Grassy Areas'] },
    ],
    usedBy: ['CyberAcme Upgrades'],
  },
  {
    id: 'storage-drive',
    name: 'Storage Drive',
    image: '/images/Storage_Drive.webp',
    tier: 'enhanced',
    value: 10,
    description: 'Drive Salvage. A potential treasure trove of colony-era data.',
    salvageType: ['Drive'],
    sources: [
      { map: 'Dire Marsh', locations: ['Algae Ponds', 'AI Uplink'] },
      { map: 'Core Storage', locations: [] },
    ],
    usedBy: ['NuCaloric Upgrades', 'NuCaloric Vendor Unlocks', 'Traxus Vendor Unlocks'],
  },
  {
    id: 'surveillance-lens',
    name: 'Surveillance Lens',
    image: '/images/Surveillance_Lens.webp',
    tier: 'enhanced',
    value: 50,
    description: 'Lens Salvage. Restricted equipment used for high-risk military recon.',
    salvageType: ['Lens'],
    sources: [
      { map: 'Dire Marsh', locations: ['Quarantine'] },
      { map: 'Bioprinter', locations: [] },
    ],
    usedBy: ['MIDA Upgrades and Barters'],
  },

  // STANDARD
  {
    id: 'unstable-biomass',
    name: 'Unstable Biomass',
    image: '/images/Unstable_Biomass.webp',
    tier: 'standard',
    value: 10,
    description: 'Plant/Chempack/Biostrip Salvage. A sample of unidentifiable biomass that has molecularly destabilized.',
    salvageType: ['Plant', 'Chempack', 'Biostrip'],
    sources: [
      { map: 'Perimeter', locations: ['Hauler', 'Overflow'] },
      { map: 'Dire Marsh', locations: ['Algae Ponds', 'Greenhouse'] },
    ],
    usedBy: ['Patch Kits', 'CyberAcme Upgrades', 'NuCaloric Upgrades and Barters'],
  },
  {
    id: 'unstable-diode',
    name: 'Unstable Diode',
    image: '/images/Unstable_Diode.webp',
    tier: 'standard',
    value: 10,
    description: 'Drive/Circuit Salvage. A diode that has molecularly destabilized.',
    salvageType: ['Drive', 'Circuit'],
    sources: [
      { map: 'Perimeter', locations: ['North Relay', 'South Relay'] },
      { map: 'Outpost', locations: ['Flight Control', 'Dormitories'] },
    ],
    usedBy: ['Shield Charges', 'CyberAcme Upgrades', 'Sekiguchi Upgrades and Barters'],
  },
  {
    id: 'unstable-gel',
    name: 'Unstable Gel',
    image: '/images/Unstable_Gel.webp',
    tier: 'standard',
    value: 10,
    description: 'Resin/Node Salvage. A sample of resorcinol-formaldehyde gel that has molecularly destabilized.',
    salvageType: ['Resin', 'Node'],
    sources: [
      { map: 'Dire Marsh', locations: ['Bio-Research'] },
      { map: 'Outpost', locations: ['Orientation', 'Processing'] },
    ],
    usedBy: ['Volt Battery', 'CyberAcme Upgrades', 'Arachne Upgrades and Barters'],
  },
  {
    id: 'unstable-gunmetal',
    name: 'Unstable Gunmetal',
    image: '/images/Unstable_Gunmetal.webp',
    tier: 'standard',
    value: 10,
    description: 'Filament/Rod/Wire Salvage. A piece of gunmetal that has molecularly destabilized.',
    salvageType: ['Filament', 'Rod', 'Wire'],
    sources: [
      { map: 'Perimeter', locations: ['Station'] },
      { map: 'Dire Marsh', locations: ['AI Uplink', 'Maintenance'] },
    ],
    usedBy: ['Light Ammo', 'CyberAcme Upgrades', 'Traxus Upgrades and Barters'],
  },
  {
    id: 'unstable-lead',
    name: 'Unstable Lead',
    image: '/images/Unstable_Lead.webp',
    tier: 'standard',
    value: 10,
    description: 'Compound/Lens Salvage. A chunk of lead that has molecularly destabilized.',
    salvageType: ['Compound', 'Lens'],
    sources: [
      { map: 'Dire Marsh', locations: ['Quarantine', 'Complex'] },
      { map: 'Outpost', locations: ['Airfield'] },
    ],
    usedBy: ['Heavy Ammo', 'CyberAcme Upgrades', 'MIDA Upgrades and Barters'],
  },
]

export function getMaterialById(id: string): Material | undefined {
  return materials.find(m => m.id === id)
}
